# Generated by Django 3.2.22 on 2024-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorID', models.CharField(default='default_test', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('year', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=512)),
                ('abstract', models.TextField()),
                ('authors', models.ManyToManyField(related_name='papers', to='IntelliQuest_v1.Author')),
            ],
        ),
    ]
